name: My first GitHub Action
run-name: ${{ github.actor }} is running tests
on: [push]

jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    steps:
      # 1. Récupérer le code de votre dépôt
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Installer Python sur la machine virtuelle
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Modifiez selon votre version

      # 3. Installer les dépendances
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 4. Exécuter les tests
      - name: Run tests
        run: pytest

      # 5. Générer le rapport de couverture
      - name: Generate coverage report
        run: coverage html

      # 6. Sauvegarder l'artefact (généralement le dossier 'htmlcov/' pour coverage)
      - name: Save coverage report as artifact
        uses: actions/upload-artifact@v4
        with: 
          name: rapport-couverture
          path: htmlcov/ # Coverage génère par défaut un dossier nommé htmlcov
          retention-days: 1

